### ISSUE TITLE
Credentials generated by Analyst user unable to pull data from API

### ISSUE THREAD

**Issue by hashimg** [googleapis/python-analytics-data#361]
Environment details:
- Python version: 3.9.9
- pip version: 23.1.2
- google-analytics-data version: 0.16.2

We encountered this error where if we are using credentials generated by a **user that has Analyst permission**, we get a `User does not have sufficient permissions` but then if we downgrade that to **Viewer** we are able to use the API and pull the data.

**Comment by parthea** [comment]
Thanks for reporting this issue. Please use the resources on [this support page](https://developers.google.com/analytics/devguides/reporting/data/v1/help) to reach out directly to the API team as this is not something that can be fixed in the client library.

Please also submit feedback via the `Contact Us` button on the page below which mentions that `Analyst` includes the permission of the `Viewer role`
https://support.google.com/analytics/answer/9305587?hl=en#zippy=%2Cgoogle-analytics

I'm going to close this issue but please feel free to open a new issue with more information.
